"""Writes the contracts' ABIs from Foundry's build output into the app, or checks they match.

    cd evm && forge build && python3 script/export_abi.py [--check]
"""
import json, os, sys

EVM = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(EVM, "..", "app", "src", "lib", "robinhood", "abi.generated.ts")
NAMES = ["OthelloFactory", "OthelloCircle"]

parts = ["// Generated by evm/script/export_abi.py from Foundry's build output. Do not edit.\n"]
for n in NAMES:
    with open(os.path.join(EVM, "out", f"{n}.sol", f"{n}.json")) as f:
        abi = json.load(f)["abi"]
    parts.append(f"\nexport const {n[0].lower() + n[1:]}Abi = {json.dumps(abi, indent=2)} as const;\n")
text = "".join(parts)

if "--check" in sys.argv:
    with open(OUT) as f:
        if f.read() != text:
            sys.exit("app/src/lib/robinhood/abi.generated.ts is stale: run evm/script/export_abi.py")
    print("abi.generated.ts matches the build")
else:
    with open(OUT, "w") as f:
        f.write(text)
    print("wrote", os.path.relpath(OUT))
