/**
 * Robinhood Stock Tokens, as Robinhood's public registry lists them: symbol and name only. Snapshot of
 * GET https://api.robinhood.com/rhj/assets (documented at https://docs.robinhood.com/chain/stock-token-apis/), taken
 * 2026-10-03: 194 active assets, every one deployed on Robinhood Chain mainnet (chain id 4663). The registry lists no
 * testnet addresses; five of these tickers also exist on testnet, sent by Robinhood's testnet faucet
 * (testnet-stocks.ts, checked 2026-10-04). Names have Robinhood's " • Robinhood Token" suffix removed.
 *
 * Deliberately left out: contract addresses (the release gate allows no address in the page but USDG and the trusted
 * factory and the five pinned testnet Stock Tokens, ops/trust-config.ts) and prices (Robinhood's terms of service
 * restrict making its services available to third parties). The Robinhood assets page lists the ones not on testnet as
 * needing mainnet.
 */
export const STOCK_TOKENS_SNAPSHOT = "2026-10-03";
export const STOCK_TOKENS_SOURCE = "https://docs.robinhood.com/chain/stock-token-apis/";

/** [symbol, name] */
export const STOCK_TOKENS: readonly (readonly [string, string])[] = [
  ["AAOI", "Applied Optoelectronics"],
  ["AAPL", "Apple"],
  ["ABCL", "Abcellera Biologics"],
  ["ADBE", "Adobe"],
  ["AEHR", "Aehr"],
  ["AEIS", "Advanced Energy"],
  ["ALAB", "Astera Labs, Inc."],
  ["AMAT", "Applied Materials"],
  ["AMBA", "Ambarella"],
  ["AMC", "AMC Entertainment"],
  ["AMD", "AMD"],
  ["AMKR", "Amkor Technology"],
  ["AMZN", "Amazon"],
  ["ANET", "Arista"],
  ["APLD", "Applied Digital"],
  ["APP", "AppLovin"],
  ["ASML", "ASML Holding NV"],
  ["ASTS", "AST SpaceMobile"],
  ["AUR", "Aurora Innovation"],
  ["AVAV", "AeroVironment"],
  ["AVGO", "Broadcom"],
  ["AXON", "Axon"],
  ["AXTI", "AXT"],
  ["BA", "Boeing"],
  ["BABA", "Alibaba"],
  ["BB", "Blackberry"],
  ["BE", "Bloom Energy"],
  ["BND", "Vanguard Total Bond Market ETF"],
  ["BULL", "Webull"],
  ["CBRS", "Cerebras Systems"],
  ["CCL", "Carnival Corporation"],
  ["CEG", "Constellation Energy"],
  ["CELH", "Celsius"],
  ["CIEN", "Ciena"],
  ["CLOV", "Clover Health Investments"],
  ["CLS", "Celestica"],
  ["CLSK", "CleanSpark"],
  ["COHR", "Coherent"],
  ["COIN", "Coinbase"],
  ["COST", "Costco"],
  ["CRCL", "Circle Internet Group"],
  ["CRDO", "Credo Technology Group"],
  ["CRM", "Salesforce"],
  ["CRWD", "CrowdStrike Holdings"],
  ["CRWV", "CoreWeave"],
  ["CSCO", "Cisco Systems"],
  ["CTSH", "Cognizant"],
  ["CVNA", "Carvana"],
  ["DDOG", "Datadog"],
  ["DELL", "Dell"],
  ["DJT", "Trump Media & Technology Group"],
  ["DOCN", "DigitalOcean"],
  ["ELF", "e.l.f. Beauty"],
  ["EWT", "iShares MSCI Taiwan Capped ETF"],
  ["EWY", "iShares MSCI South Korea fund"],
  ["F", "Ford Motor"],
  ["FICO", "Fair Isaac"],
  ["FIG", "Figma"],
  ["FISV", "Fiserv"],
  ["FIX", "Comfort Systems"],
  ["FLNC", "Fluence Energy"],
  ["FLY", "Firefly Aerospace Inc."],
  ["FTNT", "Fortinet"],
  ["FUTU", "Futu Holdings"],
  ["GE", "General Electric"],
  ["GEV", "GE Vernova"],
  ["GLD", "SPDR Gold Trust"],
  ["GLW", "Corning"],
  ["GLXY", "Galaxy Digital Inc."],
  ["GME", "GameStop"],
  ["GOOGL", "Alphabet Class A"],
  ["HII", "Huntington Ingalls"],
  ["HIMS", "Hims & Hers Health"],
  ["HPE", "HP Enterprise"],
  ["HWM", "Howmet Aerospace"],
  ["IBM", "IBM"],
  ["IBRX", "ImmunityBio,"],
  ["INDA", "iShares MSCI India ETF"],
  ["INFQ", "Infleqtion"],
  ["INOD", "Innodata"],
  ["INTC", "Intel"],
  ["INTU", "Intuit"],
  ["IONQ", "IonQ"],
  ["IREN", "IREN Limited"],
  ["JBL", "Jabil Inc."],
  ["JNJ", "Johnson & Johnson"],
  ["JOBY", "Joby Aviation"],
  ["KLAC", "KLA"],
  ["KSS", "Kohls Corporation"],
  ["KTOS", "Kratos Defense & Security Solutions"],
  ["LHX", "L3Harris"],
  ["LITE", "Lumentum"],
  ["LLY", "Eli Lilly"],
  ["LMT", "Lockheed"],
  ["LRCX", "Lam Research Corp"],
  ["LULU", "Lululemon"],
  ["LUNR", "Intuitive Machines"],
  ["MDB", "MongoDB"],
  ["META", "Meta Platforms"],
  ["MOD", "Modine"],
  ["MPWR", "Monolithic Power Systems"],
  ["MRNA", "Moderna"],
  ["MRVL", "Marvell Technology"],
  ["MSFT", "Microsoft"],
  ["MSTR", "Strategy Inc."],
  ["MTSI", "MACOM"],
  ["MU", "Micron Technology"],
  ["MXL", "MaxLinear"],
  ["NAVN", "Navan"],
  ["NBIS", "Nebius Group"],
  ["NET", "Cloudflare, Inc. Class A common stock"],
  ["NFLX", "Netflix"],
  ["NNE", "Nano Nuclear Energy"],
  ["NOW", "ServiceNow"],
  ["NU", "Nu"],
  ["NVDA", "NVIDIA"],
  ["NVTS", "Navitas Semiconductor"],
  ["OKLO", "Oklo"],
  ["ON", "ON Semiconductor"],
  ["ONTO", "Onto Innovation"],
  ["ORCL", "Oracle"],
  ["OUST", "Ouster"],
  ["P", "Everpure"],
  ["PANW", "Palo Alto Networks"],
  ["PATH", "UiPath"],
  ["PENG", "Penguin Solutions"],
  ["PFE", "Pfizer"],
  ["PL", "Planet Labs"],
  ["PLTR", "Palantir Technologies"],
  ["POET", "POET Technologies"],
  ["POWL", "Powell Industries"],
  ["PR", "Permian Resources"],
  ["PWR", "Quanta"],
  ["QBTS", "D-Wave Quantum Inc. Common Stock"],
  ["QCOM", "Qualcomm"],
  ["QQQ", "Invesco QQQ"],
  ["QUBT", "Quantum Computing"],
  ["RBLX", "Roblox"],
  ["RCAT", "Red Cat"],
  ["RDDT", "Reddit"],
  ["RDW", "Redwire"],
  ["RGTI", "Rigetti Computing"],
  ["RIVN", "Rivian Automotive"],
  ["RKLB", "Rocket Lab Corporation"],
  ["RUN", "Sunrun"],
  ["SATS", "EchoStar"],
  ["SCHD", "Schwab US Dividend Equity ETF"],
  ["SGOV", "iShares 0-3 Month Treasury Bond"],
  ["SHOP", "Shopify"],
  ["SHY", "iShares 1-3 Year Treasury Bond ETF"],
  ["SIMO", "Silicon Motion"],
  ["SKHY", "SK hynix Inc. American Depositary Shares"],
  ["SLS", "SELLAS Life Sciences"],
  ["SLV", "iShares Silver Trust"],
  ["SMCI", "Super Micro Computer"],
  ["SMH", "VanEck Semiconductor ETF"],
  ["SMR", "NuScale Power"],
  ["SNAP", "Snap"],
  ["SNDK", "Sandisk Corporation"],
  ["SNOW", "Snowflake"],
  ["SOFI", "SoFi Technologies"],
  ["SOUN", "SoundHound AI"],
  ["SOXX", "iShares Semiconductor ETF"],
  ["SPCX", "Space Exploration Technologies Corp. Class A Common Stock"],
  ["SPMO", "Invesco S&P 500 Momentum ETF"],
  ["SPY", "SPDR S&P 500 ETF Trust"],
  ["TE", "T1 Energy"],
  ["TEAM", "Atlassian Corporation"],
  ["TEM", "Tempus AI"],
  ["TER", "Teradyne"],
  ["TSEM", "Tower Semiconductor"],
  ["TSLA", "Tesla"],
  ["TSM", "Taiwan Semiconductor Manufacturing"],
  ["TTD", "Trade Desk"],
  ["TTWO", "Take-Two Interactive Software"],
  ["UMC", "United Microelectronics"],
  ["UNH", "UnitedHealth"],
  ["UPS", "UPS"],
  ["USAR", "USA Rare Earth"],
  ["USO", "United States Oil Fund"],
  ["VICR", "Vicor"],
  ["VRT", "Vertiv"],
  ["VSAT", "ViaSat"],
  ["VST", "Vistra"],
  ["VTI", "Vanguard Morningstar Total Stock Market ETF"],
  ["WDAY", "Workday"],
  ["WDC", "Western Digital"],
  ["WULF", "TeraWulf"],
  ["WYFI", "WhiteFiber, Inc."],
  ["XLK", "State Street Technology Select Sector SPDR ETF"],
  ["XNDU", "Xanadu Quantum"],
  ["XOM", "ExxonMobil Holdings Corporation"],
  ["ZM", "Zoom"],
  ["ZS", "Zscaler"],
];
